paths:
 /api/products/:
  get:
   summary: Obtener todos los productos
   tags:
    - Products
   responses:
    "200":
     description: Los productos se obtuvieron de manera correcta!
     content:
      application/json:
       schema:
        type: array
        items:
         $ref: "#components/schemas/Products"
    "500":
     description: Error interno del servidor
  post:
   summary: Agregar producto
   tags:
    - Products
   requestBody:
    required: true
    content:
     application/json:
      schema:
       $ref: "#components/requestBodies/UpdateProduct"
   responses:
    "200":
     description: El producto se añadio de forma correcta
     content:
      application/json:
       schema:
        type: objet
        properties:
         status:
          type: string
         payload:
          $ref: "#components/schemas/Rpduct"
    "500":
     description: Error interno del servidor

components:
 schemas:
  Products:
   type: object
   properties:
    _id:
     type: ObjectId
     description: id del producto
    name:
     type: string
     description: Nombre del producto
    specie:
     type: string
     description: categoria del producto
    birthDate:
     type: string
     description: fecha del producto
    adopted:
     type: boolean
     description: indica si el producto fue agregado
    owner:
     type: ObkectId
     description: id del propietario
    image:
     type: string
     description: foto del producto
   example:
    _id: ObjectId("gsa98273skjhgda8912")
    name: Kawasaki
    specie: moto
    bithDate: 12/10/2020
    adopted: true
    owner: ObjectId("gsa98273skjhgda582")
    image: "http:www.imagen/moto.jpg"
 requestBodies:
  UpdatePet:
   type: object
   properties:
    name:
     type: string
     description: nombre del producto
    specie:
     type: string
     description: categoria del producto
    birthDate:
     type: string
     description: fecha del producto
   example:
    name: Kawasaki
    specie: Moto
    birthDate: 12/10/2020
    